const rightsHolders = [
  "Africa Gomez",
  "Alex Payne",
  "Becky Cameron",
  "Botanical Society of Britain and Ireland and Biological Records Centre",
  "Brian Robinson",
  "Charlotte Varela",
  "Christine Tansey",
  "Darrel Watts",
  "Dave Purchase",
  "David Earl",
  "Downing",
  "James",
  "Judèé Époh-Éèduj Hopè",
  "Kian Hayles-Cotton",
  "Kyle Martyn-Clark",
  "M Firth Robertshaw",
  "Richard Andrew Law",
  "Richard Draper",
  "Sara Steeles-Yates",
  "Smriti S.",
  "Stichting Observation International",
  "Tina Booth",
  "angharadlois",
  "benmountford07",
  "considerthelilies",
  "hannahvwarren",
  "hazeybabes",
  "herbie72",
  "koaliah",
  "markyt63",
  "mnt99york",
  "naturenab",
  "nick_hardcastle",
  "patot",
  "roryga01",
  "vegantam1"
]

export default rightsHolders
