const species = [
  'Asplenium adiantum-nigrum',
  'Asplenium ceterach',
  'Asplenium ruta-muraria',
  'Asplenium scolopendrium',
  'Asplenium scolopendrium scolopendrium',
  'Asplenium trichomanes',
  'Asplenium viride',
  'Athyrium filix-femina',
  'Botrychium lunaria',
  'Chara vulgaris',
  'Cryptogramma crispa',
  'Cyrtomium falcatum',
  'Cyrtomium fortunei',
  'Cystopteris fragilis',
  'Dryopteris affinis',
  'Dryopteris borreri',
  'Dryopteris cambrensis',
  'Dryopteris carthusiana',
  'Dryopteris dilatata',
  'Dryopteris filix-mas',
  'Dryopteris oreades',
  'Equisetum arvense',
  'Equisetum fluviatile',
  'Equisetum palustre',
  'Equisetum sylvaticum',
  'Equisetum telmateia',
  'Gymnocarpium dryopteris',
  'Gymnocarpium robertianum',
  'Huperzia selago',
  'Hymenophyllum tunbrigense',
  'Hymenophyllum wilsonii',
  'Lycopodium alpinum',
  'Lycopodium clavatum',
  'Ophioglossum vulgatum',
  'Oreopteris limbosperma',
  'Osmunda regalis',
  'Phegopteris connectilis',
  'Polypodium interjectum',
  'Polypodium vulgare',
  'Polystichum aculeatum',
  'Polystichum setiferum',
  'Pteridium aquilinum',
  'Struthiopteris spicant',
]

export default species
